# ML Cup Event #3

In [1]:
import pandas as pd
import numpy as np

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import sklearn
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The scikit-learn version is 0.23.2.


In [3]:
import os
os.getcwd()

'/Users/jacquelinemak/MMA /MMA 869 Machine Learning & AI'

In [4]:
df = pd.read_csv("diabetes_train.csv")

Id_col = 'Id'
target_col = 'diabetes'
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Id                  576 non-null    int64  
 1   num_times_pregnant  576 non-null    int64  
 2   plasma_glucose      576 non-null    int64  
 3   DBP                 576 non-null    int64  
 4   triceps_skin        576 non-null    int64  
 5   serum_insulin       576 non-null    int64  
 6   BMI                 576 non-null    float64
 7   pedigree            576 non-null    float64
 8   age                 576 non-null    int64  
 9   diabetes            576 non-null    int64  
dtypes: float64(2), int64(8)
memory usage: 45.1 KB


Id  num_times_pregnant  plasma_glucose  DBP  triceps_skin  serum_insulin  \
0  358                  13             129    0            30              0   
1   74                   4             129   86            20            270   
2  353                   3              61   82            28              0   
3  498                   2              81   72            15             76   
4  146                   0             102   75            23              0   

    BMI  pedigree  age  diabetes  
0  39.9     0.569   44         1  
1  35.1     0.231   23         0  
2  34.4     0.243   46         0  
3  30.1     0.547   25         0  
4   0.0     0.572   21         0

In [5]:
#check for missing data 
df.isna().sum()

Id                    0
num_times_pregnant    0
plasma_glucose        0
DBP                   0
triceps_skin          0
serum_insulin         0
BMI                   0
pedigree              0
age                   0
diabetes              0
dtype: int64

In [6]:
from sklearn.preprocessing import StandardScaler

# Normalize the data

In [9]:
scaler = StandardScaler()
features = ['num_times_pregnant', 'plasma_glucose', 'DBP', 'triceps_skin', 'serum_insulin', 'BMI', 'pedigree', 'age']
X[features] = scaler.fit_transform(X[features])

# MinMax

In [7]:
from sklearn.preprocessing import MinMaxScaler


In [10]:
# scaler = MinMaxScaler()
# features = ['num_times_pregnant', 'plasma_glucose', 'DBP', 'triceps_skin', 'serum_insulin', 'BMI', 'pedigree', 'age']
# X[features] = scaler.fit_transform(X[features])


In [9]:
from sklearn.model_selection import train_test_split

X = df.drop([Id_col, target_col], axis=1)
y = df[target_col]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
X.info()
X.shape
X.head()

X_train.info()
X_train.shape
X_train.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   num_times_pregnant  576 non-null    int64  
 1   plasma_glucose      576 non-null    int64  
 2   DBP                 576 non-null    int64  
 3   triceps_skin        576 non-null    int64  
 4   serum_insulin       576 non-null    int64  
 5   BMI                 576 non-null    float64
 6   pedigree            576 non-null    float64
 7   age                 576 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 36.1 KB


(576, 8)

num_times_pregnant  plasma_glucose  DBP  triceps_skin  serum_insulin   BMI  \
0                  13             129    0            30              0  39.9   
1                   4             129   86            20            270  35.1   
2                   3              61   82            28              0  34.4   
3                   2              81   72            15             76  30.1   
4                   0             102   75            23              0   0.0   

   pedigree  age  
0     0.569   44  
1     0.231   23  
2     0.243   46  
3     0.547   25  
4     0.572   21

<class 'pandas.core.frame.DataFrame'>
Int64Index: 460 entries, 437 to 102
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   num_times_pregnant  460 non-null    int64  
 1   plasma_glucose      460 non-null    int64  
 2   DBP                 460 non-null    int64  
 3   triceps_skin        460 non-null    int64  
 4   serum_insulin       460 non-null    int64  
 5   BMI                 460 non-null    float64
 6   pedigree            460 non-null    float64
 7   age                 460 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 32.3 KB


(460, 8)

num_times_pregnant  plasma_glucose  DBP  triceps_skin  serum_insulin  \
437                   6             102   82             0              0   
63                    7             142   60            33            190   
208                   1             119   44            47             63   
60                    8             143   66             0              0   
15                    0             123   88            37              0   

      BMI  pedigree  age  
437  30.8     0.180   36  
63   28.8     0.687   61  
208  35.5     0.280   25  
60   34.9     0.129   41  
15   35.2     0.197   29

In [11]:
np.bincount(y)

array([377, 199])

# Build Model 
# Decision Tree

In [12]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(max_depth=2)
clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2)

# Estimate Model Performance

In [13]:
from sklearn.metrics import confusion_matrix

pred_val = clf.predict(X_val)
pred_val

confusion_matrix(y_val, pred_val)

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

array([[78,  3],
       [19, 16]])

In [14]:
from sklearn.metrics import classification_report

print(classification_report(y_val, pred_val))

              precision    recall  f1-score   support

           0       0.80      0.96      0.88        81
           1       0.84      0.46      0.59        35

    accuracy                           0.81       116
   macro avg       0.82      0.71      0.73       116
weighted avg       0.82      0.81      0.79       116



# Random Forest

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
clf_model_2 = RandomForestClassifier()   
clf_model_2.fit(X_train,y_train)


RandomForestClassifier()

In [17]:
#Estimate Model Performance

pred_rf = clf_model_2.predict(X_val)
pred_rf

confusion_matrix(y_val, pred_rf)

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1])

array([[73,  8],
       [15, 20]])

In [18]:
print(classification_report(y_val, pred_rf))

              precision    recall  f1-score   support

           0       0.83      0.90      0.86        81
           1       0.71      0.57      0.63        35

    accuracy                           0.80       116
   macro avg       0.77      0.74      0.75       116
weighted avg       0.79      0.80      0.79       116



# Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression

clf_model_3 = LogisticRegression()

In [20]:
clf_model_3.fit(X_train,y_train)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [21]:
#Estimate Model Performance

pred_lr = clf_model_3.predict(X_val)
pred_lr

confusion_matrix(y_val, pred_lr)

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1])

array([[74,  7],
       [14, 21]])

In [22]:
print(classification_report(y_val, pred_lr))

              precision    recall  f1-score   support

           0       0.84      0.91      0.88        81
           1       0.75      0.60      0.67        35

    accuracy                           0.82       116
   macro avg       0.80      0.76      0.77       116
weighted avg       0.81      0.82      0.81       116



# Create Submission File on Test Data

In [23]:
test_df = pd.read_csv('diabetes_test.csv')

In [24]:
X_test = test_df.drop([Id_col], axis=1)

In [25]:
# Use your model to make predictions
pred_test = clf_model_3.predict(X_test)

In [26]:
# We will look at the predicted prices to ensure we have something sensible.
print(pred_test)

my_submission = pd.DataFrame({'Id': test_df.Id, 'Predicted': pred_test})

my_submission.head()

# you could use any filename. We choose submission here
my_submission.to_csv('JM_submission3.csv', index=False)

[0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 1
 0 0 1 0 1 1 0 0 1 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 1 0 1 0 1 1 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0
 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 1 1 0 1 1 0 0 0 1 0 0 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 0 0 0 1 0 0 0]


Id  Predicted
0  669          0
1  325          0
2  625          0
3  691          0
4  474          0